django/project/apps/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    path('add/store/', views.AddStore.as_view(), name='addStore'),
    path('store/<int:id>/', views.StoreDetail.as_view(), name='storeDetail'),
    path('store/', views.StoreList.as_view(), name='storeList'),

    path('add/stock/', views.AddStock.as_view(), name='addStock'),
    path('stock/<int:id>/', views.StockDetail.as_view(), name='stockDetail'),
    path('stock/', views.StockList.as_view(), name='stockList'),

    path('add/item/', views.AddItem.as_view(), name='addItem'),
    path('item/<int:id>/', views.ItemDetail.as_view(), name='itemDetail'),
    path('item/', views.ItemList.as_view(), name='itemList'),

    path('add/client/', views.AddPerson.as_view(), name='addPerson'),
    path('client/<int:id>/', views.PersonDetail.as_view(), name='personDetail'),
    path('client/', views.PersonList.as_view(), name='personList'),

    path('add/sale/', views.AddInvoice.as_view(), name='addInvoice'),
    #path('sale/<int:id>/', views.InvoiceDetail.as_view(), name='invoiceDetail'),
    #path('sale/', views.InvoiceList.as_view(), name='invoiceList'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.authtoken.views import ObtainAuthToken

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/authentication/', ObtainAuthToken.as_view(), name='apiAuthentication'),
    path('api/', include('project.apps.api.urls', namespace='api')),
    path('', include('project.apps.core.urls', namespace='core')),
    path('', include('project.apps.store.urls', namespace='store')),
]

django/project/apps/store/models.py
from django.db import models
from django.urls import reverse_lazy

from ..utils.models import BaseModel
from ..core.models import User


# Store Information
class Store(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=45)
    address = models.TextField(max_length=90)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.name

    def getAbsoluteUrl(self):
        return reverse_lazy('store:storeDetail', kwargs={'id': self.id})

    class Meta:
        ordering = ('name',)


# Product Information
class Item(BaseModel):
    name = models.CharField(max_length=45)
    description = models.TextField(max_length=80)

    def __str__(self):
        return self.name

    def getAbsoluteUrl(self):
        return reverse_lazy('store:itemDetail', kwargs={'id': self.id})

    class Meta:
        ordering = ('name', 'description')


# Product Stock
class Stock(BaseModel):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - quantity: {}'.format(
            self.item.name,
            self.quantity
        )

    def getAbsoluteUrl(self):
        return reverse_lazy('store:stockDetail', kwargs={'id': self.pk})

    class Meta:
        ordering = ('store',)


# Client Information
class Person(BaseModel):
    name = models.CharField(max_length=60)
    lastName = models.CharField(max_length=60)
    identification = models.CharField(max_length=10, unique=True)
    address = models.TextField(max_length=90)
    email = models.EmailField()

    def __str__(self):
        return '{} {} - {}'.format(
            self.name,
            self.lastName,
            self.identification
        )

    def getAbsoluteUrl(self):
        return reverse_lazy('store:personDetail', kwargs={'id': self.pk})

    class Meta:
        ordering = ('name', 'lastName', 'identification')


# Invoice Information
class Invoice(BaseModel):
    number = models.BigIntegerField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    detail = models.ManyToManyField(Item, through='InvoiceDetail')

    def __str__(self):
        return '{} - {} | {}'.format(
            self.number,
            self.person,
            self.date
        )

    def getAbsoluteUrl(self):
        return reverse_lazy('store:invoiceDetail', kwargs={'id': self.pk})

    class Meta:
        ordering = ('store', 'date')


# Weak entity to Invoice
class InvoiceDetail(BaseModel):
    quantity = models.IntegerField()
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - quantity: {}'.format(
            self.item,
            self.quantity
        )

    def getAbsoluteUrl(self):
        return reverse_lazy('store:invoiceDetailDetail', kwargs={'id': self.pk})

    class Meta:
        ordering = ('invoice__store', 'invoice__date')

django/project/apps/store/forms.py
from django.core.exceptions import ValidationError
from django.forms import (
    ModelForm,
    ModelChoiceField,
    Select
)

from . import models


class StoreForm(ModelForm):
    class Meta:
        model = models.Store
        fields = ('name', 'address', 'email')


class ItemForm(ModelForm):
    class Meta:
        model = models.Item
        fields = ('name', 'description')


class StockForm(ModelForm):
    class Meta:
        model = models.Stock
        fields = ('store', 'quantity', 'item')
        widgets = {
            'item': Select(
                attrs={'class': 'form-control'}),
            'store': Select(
                attrs={'class': 'form-control'})
        }

    def __init__(self, user, *args, **kwargs):
        super(StockForm, self).__init__(*args, **kwargs)
        store = self.fields['store']
        store.queryset = models.Store.objects.filter(available=True, user=user)


class PersonForm(ModelForm):
    class Meta:
        model = models.Person
        fields = (
            'name',
            'lastName',
            'identification',
            'address',
            'email'
        )


class InvoiceForm(ModelForm):
    class Meta:
        model = models.Invoice
        fields = (
            'number',
            'store',
            'person',
        )

django/project/apps/store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView

from ..utils.views import BaseUpdateView, BaseListView
from . import forms
from . import models


# Create your views here.
class Index(TemplateView):
    http_method_names = ('get')
    template_name = 'store/index.html'


class AddStore(LoginRequiredMixin, CreateView):
    http_method_names = ('get', 'post')
    form_class = forms.StoreForm
    template_name = 'store/store/addStore.html'

    # Add user to 'Store' before commit on save
    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class StoreDetail(LoginRequiredMixin, BaseUpdateView):
    form_class = forms.StoreForm
    model = models.Store
    template_name = 'store/store/storeDetail.html'

    # Extra filter for user and his 'Stores'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class StoreList(LoginRequiredMixin, BaseListView):
    model = models.Store
    template_name = 'store/store/storeList.html'

    # Extra filter for user and his 'Stores'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class AddStock(LoginRequiredMixin, CreateView):
    http_method_names = ('get', 'post')
    form_class = forms.StockForm
    template_name = 'store/stock/addStock.html'

    # To send paramter 'user' to the StockForm
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class StockDetail(LoginRequiredMixin, BaseUpdateView):
    form_class = forms.StockForm
    model = models.Stock
    template_name = 'store/stock/stockDetail.html'

    # To send paramter 'user' to the StockForm
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    # Extra filter for 'Stores', 'Stocks' and 'User'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(store__user=self.request.user)
        return queryset


class StockList(LoginRequiredMixin, BaseListView):
    model = models.Stock
    template_name = 'store/stock/stockList.html'

    # extra filter
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(store__user=self.request.user)
        return queryset


class AddItem(LoginRequiredMixin, CreateView):
    http_method_names = ('get', 'post')
    form_class = forms.ItemForm
    template_name = 'store/item/addItem.html'


class ItemDetail(LoginRequiredMixin, BaseUpdateView):
    form_class = forms.ItemForm
    model = models.Item
    template_name = 'store/item/itemDetail.html'


class ItemList(LoginRequiredMixin, BaseListView):
    model = models.Item
    template_name = 'store/item/itemList.html'


class AddPerson(LoginRequiredMixin, CreateView):
    http_method_names = ('get', 'post')
    form_class = forms.PersonForm
    template_name = 'store/person/addPerson.html'


class PersonDetail(LoginRequiredMixin, BaseUpdateView):
    form_class = forms.PersonForm
    model = models.Person
    template_name = 'store/person/personDetail.html'


class PersonList(LoginRequiredMixin, BaseListView):
    model = models.Person
    template_name = 'store/person/personList.html'


class AddInvoice(LoginRequiredMixin, CreateView):
    http_method_names = ('get', 'post')
    form_class = forms.InvoiceForm
    template_name = 'store/invoice/addInvoice.html'

django/project/apps/store/templates/store/person/addPerson.html
{% extends 'core/base.html' %}


{% block title %}Add Client{% endblock title %}


{% block content %}
    <div class="container">
      <br>
      <h1 class="text-center">Add Client</h1>
      <br>
      {% include 'store/person/personForm.html' %}

    </div>
{% endblock content %}

django/project/apps/store/templates/store/person/personDetail.html
{% extends 'core/base.html' %}


{% block title %}Client Detail{% endblock title %}


{% block content %}
    <div class="container">
      <br>
      <h1 class="text-center">Client Detail</h1>
      <br>
      {% include 'store/person/personForm.html' %}

    </div>
{% endblock content %}

django/project/apps/store/templates/store/person/personForm.html
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" autofocus required class="form-control" id="name" name="name" placeholder="Enter name.." value="{{form.name.value|default:''}}">
        </div>

        <div class="form-group">
          <label for="lastName">Last Name</label>
          <input type="text" autofocus required class="form-control" id="lastName" name="lastName" placeholder="Enter last name.." value="{{form.lastName.value|default:''}}">
        </div>

        <div class="form-group">
          <label for="identification">Identification</label>
          <input type="text" autofocus required class="form-control" id="identification" name="identification" placeholder="Enter identification.." value="{{form.identification.value|default:''}}">
        </div>

        <div class="form-group">
          <label for="address">Address</label>
          <textarea class="form-control" required name="address" id="address" rows="2" placeholder="Enter address..">{{form.address.value|default:''}}</textarea>
        </div>

        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="your@email.com" value="{{form.email.value|default:''}}">
        </div>
        
        {% if form.errors %}
        {% include 'store/errors.html' %}
        {% endif %}
          
        <button type="submit" class="btn btn-success">Create</button>
        <a class="btn btn-info" href="{% url 'store:index' %}">Go to Index</a>
      </form>

django/project/apps/store/templates/store/person/personList.html
{% extends 'core/base.html' %}


{% block title %}Person List{% endblock title %}


{% block content %}
    <div class="container">
      <br>
      <h1 class="text-center">Person List</h1>
      <p class="text-center">Clic to see details</p>
      <br>
      
      {% include 'store/list.html' %}
      <br>
      <a class="btn btn-success" href="{% url 'store:addPerson' %}">Add Person</a>
      <a class="btn btn-info" href="{% url 'store:index' %}">Go to Index</a>
    </div>
{% endblock content %}